### ISSUE TITLE
GetAndroidConfig in FirebaseManagement  throwing exception error

### ISSUE THREAD

**Issue by SamrawitMM** [Denys2211/Firebase-cloud-messaging#1]
`Unhandled exception. The service firebase has thrown an exception.
No HttpStatusCode was specified.
No error details were specified.
Google.GoogleApiException: Parameter validation failed for "parent" : The value did not match the regular expression ^projects/[^/]+$
   at Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   at Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   at Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteUnparsedAsync(CancellationToken cancellationToken)
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at CloudResourceManager.FirebaseManagement.GetAndroidConfig() in /home/samrawit/My-Nation/Project-firebase-automation/trial2/automation/FirebaseManagement.cs:line 207
   at CloudResourceManagers.Program.Main(String[] args) in /home/samrawit/My-Nation/Project-firebase-automation/trial2/automation/Program.cs:line 97
`
Here is the error I am getting when trying to get android configuration response, how is this issue fixed?

**Comment by SamrawitMM** [comment]
` public static AndroidAppConfig GetAndroidConfig()
        {
       
            var listAndroid = _firebaseManagementService.Projects.AndroidApps.List("projects/" + CloudManager.ProjectId).Execute();
            return _firebaseManagementService.Projects.AndroidApps.GetConfig("projects/"+ CloudManager.ProjectId +"/androidApps/" + listAndroid.Apps[0].AppId + "/config").Execute();
        }`

Removing /androidApps in the listAndroid statement fixed the issue.
Thanks
